spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

owners:
  name: "HemanthQA"
  email: "hemanthQA@gmail.com"
  address:
    hno: "1-23"
    country: "India"
  contact:
    - "9876543211"
    - "9876543212"